{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNWcRaj6gNh8iYEzybBK3Kv",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/KaviyaKannan14/R-Projects/blob/main/Twitch_and_Stream.r\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "TSnULta0gOGP",
        "outputId": "3b57bb8b-a12d-4db4-f180-8228cbfdd1b4",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 143
        }
      },
      "outputs": [
        {
          "output_type": "error",
          "ename": "SyntaxError",
          "evalue": "invalid syntax (<ipython-input-1-c92d931c9ff7>, line 40)",
          "traceback": [
            "\u001b[0;36m  File \u001b[0;32m\"<ipython-input-1-c92d931c9ff7>\"\u001b[0;36m, line \u001b[0;32m40\u001b[0m\n\u001b[0;31m    game_attributes[, release_date := sapply(strsplit(release_date, \"–\"), function(x) x[1])]\u001b[0m\n\u001b[0m                    ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"
          ]
        }
      ],
      "source": [
        "# read all data\n",
        "\n",
        "library(data.table)\n",
        "\n",
        "#############################\n",
        "# Step 1: clean and understand Steam data\n",
        "#############################\n",
        "\n",
        "# We start with two data sets: Twitch and Steam. In this step we first work on cleaning Steam data\n",
        "# There are three files. game_attributes, game_players, and game_price_changes\n",
        "#   The primary key for game_attributes is $app_id. This is app-level data on their attributes.\n",
        "#   The primary key for game_players is $app_id and $date. This is daily data for the number of players in the game\n",
        "#   The primary key for game_price_changes is $app_id and $price_change_date. This is a record of the price-changing\n",
        "#   occasions and the new prices at those occasions.\n",
        "\n",
        "# We should clean game_attributes data. $release_date is in some weird format. Make it a date variable. Discard the time\n",
        "#   aspect. $rating_text contains useful information. We want the percentage of positive ratings and the average rating number\n",
        "#   in two separate variables. For all data, keep games with the type \"game\" and with non-missing release date, rating, and reviews.\n",
        "\n",
        "# We need to clean the price change data to get daily prices. For a game-date combination, if the game_price_changes\n",
        "#   data has an observation on that day, the $price variable in that data measures the price on that day. If there is no\n",
        "#   price data on a day, we know that price did not change on that day, so its takes the previous value. For example, for\n",
        "#   game 730 (Counter-Strike: Global Offensive). The price was changed to $9.99 on 2012-11-01. Then it was changed again\n",
        "#   to $11.24 on 2012-11-22. This means that before the change on 2012-11-22, the price stayed at $9.99.\n",
        "#   By the end of this step, you should have a price data at the level of game-date. There should be no gap in dates unless\n",
        "#   for specific reasons that lead to missing data. You should then be able to merge the players data with the price data.\n",
        "\n",
        "# Finally, produce summary statistics at the game level: for each game, first compute the average daily number of players,\n",
        "#   average price, total number of price changes, number of ratings and the fraction of positive reviews, Then summarize the\n",
        "#   mean and standard deviation of these variables across games. Also, find all paid games (i.e., games with an average price\n",
        "#   above zero), and among those paid games, find 9 games with the highest average daily players. Produce summary statistics\n",
        "#   for each of these 9 games. Print these summary stats in the console. Optionally, export the summary stats into tables.\n",
        "\n",
        "# read data\n",
        "game_attributes <- fread(\"../raw/steam/game_attributes.csv\")\n",
        "game_players <- fread(\"../raw/steam/game_players.csv\")\n",
        "game_price_changes <- fread(\"../raw/steam/game_price_changes.csv\")\n",
        "\n",
        "# clean game attributes data\n",
        "game_attributes[, release_date := sapply(strsplit(release_date, \"–\"), function(x) x[1])]\n",
        "game_attributes[, release_date := as.Date(release_date, \"%d %B %Y \")]\n",
        "game_attributes[, percent_positive := as.numeric(sub(\"\\\\% of.*$\", \"\", rating_text))]\n",
        "game_attributes[, number_reviews := as.integer(gsub(\",\", \"\", sub(\"^.* of the \", \"\", sub(\" user reviews.*$\", \"\", rating_text))))]\n",
        "game_attributes <- game_attributes[!is.na(percent_positive) & !is.na(number_reviews) & !is.na(release_date)]\n",
        "\n",
        "# create game price\n",
        "game_price <- data.table(expand.grid(app_id = unique(game_price_changes$app_id), date = unique(game_players$date)))\n",
        "game_price <- game_price[app_id %in% game_attributes$app_id]\n",
        "game_price <- merge(game_price, game_price_changes, by.x = c(\"app_id\", \"date\"), by.y = c(\"app_id\", \"price_change_date\"), all.x = T)\n",
        "game_price <- merge(game_price, game_attributes[, .(app_id, release_date)], by = \"app_id\", all.x = T)\n",
        "game_price <- game_price[date >= release_date]  # keep price observations after release\n",
        "game_price$release_date <- NULL\n",
        "\n",
        "# replace missing prices    # WAY TOO SLOW...\n",
        "# game_price <- game_price[order(app_id, date)]\n",
        "# fwrite(game_price, \"../temp/test_price_data.csv\")\n",
        "# for (obs in 2:nrow(game_price)) {\n",
        "#     if (is.na(game_price$price[obs]) & game_price$app_id[obs] == game_price$app_id[obs-1]) {    # if missing price (i.e. no price change) and we're looking at the same game, replace price with previous price\n",
        "#         game_price$price[obs] <- game_price$price[obs-1]\n",
        "#         game_price$discount[obs] <- game_price$discount[obs-1]\n",
        "#     }\n",
        "# }\n",
        "\n",
        "# ChatGPT suggested using nafill (see chat history)\n",
        "game_price[, price := nafill(price, type = \"locf\"), by = app_id]\n",
        "game_price[, discount := nafill(discount, type = \"locf\"), by = app_id]\n",
        "game_price <- game_price[!is.na(price)] # eliminate observations without a price\n",
        "game_price[, price_change := price != c(price[1], price[1:(length(price)-1)]), by = app_id]\n",
        "\n",
        "# alternative: tidyverse version...\n",
        "# game_price <- game_price %>%\n",
        "#     group_by(app_id) %>%                          # Group by app_id\n",
        "#     arrange(date) %>%                             # Ensure data is sorted by date within each group\n",
        "#     fill(price, discount, .direction = \"down\")\n",
        "\n",
        "# summary stats at the game level\n",
        "game_price_players <- merge(game_price, game_players, by = c(\"app_id\", \"date\")) # didn't have all = T on purpose\n",
        "game_level_obs <- game_price_players[, .(price = mean(price),\n",
        "                                         price_change = sum(price_change),\n",
        "                                         player_count = mean(player_count)), by = app_id]\n",
        "game_level_obs <- merge(game_level_obs, game_attributes[, .(app_id, title, percent_positive, number_reviews)], by = \"app_id\")\n",
        "\n",
        "# summary stats\n",
        "summary_game <- sapply(game_level_obs[, .(price, price_change, player_count, percent_positive, number_reviews)],\n",
        "                       FUN = function(x) c(mean = mean(x), sd = sd(x), quantile(x)))\n",
        "summary_game\n",
        "\n",
        "# top 9?\n",
        "top_9_paid_games <- game_level_obs[price > 0][order(-player_count), .(app_id, title, price, price_change, player_count, percent_positive, number_reviews)][1:9]\n",
        "top_9_paid_games\n",
        "\n",
        "#############################\n",
        "# Step 2: how well associated between prices and the number of players?\n",
        "#############################\n",
        "\n",
        "# When there is a price discount, the number of players might increase if people buy the game and play it. We will look into\n",
        "#   this hypothesis.\n",
        "#   We start by looking at the 9 games. For each of these 9 games, plot the trajectory of prices and the number of players\n",
        "#   over time. Use log scale for the number of players but not for price (put them on two different axes). Do you see a correlation?\n",
        "#   Then, calculate the correlation coefficient between the log number of players and price. Then, in the graph title, mark the game\n",
        "#   and the correlation coefficient between the log number of players and price. Do you see a negative correlation, in that the higher\n",
        "#   the price, the lower the number of players?\n",
        "#   Finally, compute the correlation between log players and price for each game, and summarize the average and the distribution of this\n",
        "#   correlation. Or you can plot a histogram. Do you still find negative correlation?\n",
        "\n",
        "# plot for the top 9\n",
        "pdf(\"../output/plot_players_and_price.pdf\", width = 15, height = 15)\n",
        "par(mfrow = c(3, 3))\n",
        "for (i in 1:9) {\n",
        "    aid <- top_9_paid_games$app_id[i]\n",
        "    dat <- game_price_players[app_id == aid][order(date)]\n",
        "    corcoef <- cor(log(dat$player_count), dat$price)\n",
        "    plot(player_count ~ date, data = dat, type = 'l', lty = 2, log = \"y\", col = \"blue\",\n",
        "         main = paste(top_9_paid_games$title[i], \", corr = \", round(corcoef, 2)))\n",
        "    par(new = T)\n",
        "    plot(price ~ date, data = dat, type = 'l', axes=FALSE, xlab = \"\", ylab = \"\")\n",
        "    axis(side = 4)\n",
        "    par(new = F)\n",
        "}\n",
        "dev.off()\n",
        "\n",
        "# correlation for all games\n",
        "game_cor <- game_price_players[, .(corcoef = cor(log(player_count), price)), by = app_id]\n",
        "hist(game_cor$corcoef)\n",
        "\n",
        "\n",
        "# Now, perform a related (but different) exercise on the number of ratings and the average number of players. Note that we do\n",
        "#   not see ratings on each day for each game. We simply see an average rating. So we cannot look at how rating changes and how that's\n",
        "#   associated with the number of players. But at least we can still look at the scatter plot between the average rating and the\n",
        "#   log(average number of players) for each game. In the scatter plot, one observation is a game. Fit a line or curve between the two\n",
        "#   variables. Also write down the correlation coefficient in the graph title. What can you conclude here?\n",
        "\n",
        "pdf(\"../output/plot_players_and_rating.pdf\", width = 9, height = 9)\n",
        "plot(log(player_count) ~ percent_positive, data = game_level_obs, cex = 0.5, col = rgb(0,0,1,0.25),\n",
        "     xlab = \"percent of positive reviews\", ylab = \"log player count\",\n",
        "     main = paste0(\"correlation = \", round(cor(log(game_level_obs$player_count), game_level_obs$percent_positive), 2)))\n",
        "regline <- lm(log(player_count) ~ percent_positive, data = game_level_obs)\n",
        "abline(regline, col = rgb(0,0,1,1), lwd = 1.2)\n",
        "dev.off()\n",
        "\n",
        "\n",
        "#############################\n",
        "# Step 3: now load the Twitch streamer data\n",
        "#############################\n",
        "\n",
        "# now read Twitch data. There are two files.\n",
        "#   Data twitch_profiles has the key $streamer. This is a sample of about 10,000 streamers.\n",
        "#   Data twitch_streams' key should be each observation, which is a stream.\n",
        "#   A stream is broadcasted by $streamer on a $date, but notice that a streamer on a date can have multiple streams.\n",
        "#   Variable $viewers records how many viewers are simultaneously present in the stream. $duration is the number of hours of the stream.\n",
        "#   $unique_viewers is the number of viewers who ever appeared. $followers is the number of followers of the streamer at the time of the\n",
        "#   stream. $stream_title is the title of the stream. And $games is a list of all games that are broadcasted in the same stream.\n",
        "\n",
        "twitch_profiles <- fread(\"../raw/twitch/twitch_profiles.csv\")\n",
        "twitch_streams <- fread(\"../raw/twitch/twitch_streams.csv\")\n",
        "\n",
        "# Now, let us organize the data such that we count the total amount of viewing time for each game on each day. To do this, we have to process\n",
        "#   the data in a few steps:\n",
        "#   1. restructure the data into stream (the original level of observation)-game level. That is, we should put different\n",
        "#   games in different observations for each stream.\n",
        "#   2. for each stream, multiply the number of viewers (not the unique viewer) by the stream duration to get the viewing time (unit is viewer-hour).\n",
        "#   Then divide viewing time by the number of games. Here, we're assuming that each game gets equal amount of exposure.\n",
        "#   3. sum up the total viewing time for each game on each day, across streams. Also count how many streamers broadcasted the game on each day.\n",
        "#   Finally, because some streamers are \"big\" in that they attract many viewers, whereas other streamers are small. Compute a follower-weighted\n",
        "#   measure of the number of streamers by summing up all streamers who broadcast the game by their followers (sum followers for those who broadcast game j)\n",
        "\n",
        "# 1. separate the games and restructure the data\n",
        "twitch_streams[, stream_id := 1:length(viewers), .(streamer, date)] # create an index stream_id, so that now streamer-date-stream_id form the key\n",
        "list_games <- strsplit(twitch_streams$games, split = \", \")\n",
        "max_nr_games <- quantile(sapply(list_games, FUN = length))          # max number of games appearing in one broadcast\n",
        "twitch_stream_game_wide <- twitch_streams[, .(streamer, date, stream_id)]\n",
        "for (j in 1:max_nr_games) {\n",
        "    print(j)\n",
        "    twitch_stream_game_wide[[paste0(\"title\", j)]] <- sapply(list_games, function(x) x[j])   # arrange games one by one into columns\n",
        "}\n",
        "twitch_stream_game_long <- melt(twitch_stream_game_wide, id.vars = c(\"streamer\", \"date\", \"stream_id\"))   # now reshape into wide; note that we're using data.table melt\n",
        "twitch_stream_game_long <- twitch_stream_game_long[!is.na(value)]\n",
        "colnames(twitch_stream_game_long)[5] <- \"title\"\n",
        "twitch_stream_game_long$variable <- NULL\n",
        "\n",
        "# 2. adjust viewers\n",
        "twitch_stream_game_long <- merge(twitch_stream_game_long, twitch_streams[, .(streamer, date, stream_id, duration, viewers, followers)], by = c(\"streamer\", \"date\", \"stream_id\"), all.x = T)\n",
        "print(paste(sum(is.na(twitch_stream_game_long$duration)), \"observations have missing stream duration\"))\n",
        "twitch_stream_game_long[, n_games_in_stream := length(title), by = .(streamer, date, stream_id)]             # count how many games in the stream\n",
        "twitch_stream_game_long[, duration_per_game := duration / n_games_in_stream]\n",
        "twitch_stream_game_long[, viewing_hour_per_game := viewers * duration_per_game]\n",
        "\n",
        "# 3. sum up total viewing hour across streams\n",
        "twitch_stream_game_long[, obs_nr := 1:length(followers), by = .(title, streamer, date)]\n",
        "twitch_stream_game_long[obs_nr == 1, follower_first := followers]  # if this is the first observation for a game-streamer-date, count the follower\n",
        "twitch_viewing_hours <- twitch_stream_game_long[, .(viewing_hour = sum(viewing_hour_per_game),\n",
        "                                                    num_streamers = length(unique(streamer)),\n",
        "                                                    num_streamers_weighted = sum(follower_first, na.rm = T)), by = .(title, date)]\n",
        "\n",
        "#############################\n",
        "# Step 4: Is there an association between Twitch streaming and video game playing?\n",
        "#############################\n",
        "\n",
        "# Now we're ready to examine whether Twitch broadcasts are associated with the number of players in games\n",
        "#   To begin with, merge the Twitch data on the daily total viewing hours and the number of streamers.\n",
        "#   Drop games that do not exist in both data, but keep all dates for games that exist in both data even if\n",
        "#   that date does not have streams. Finally, keep observations after 2017-01-01.\n",
        "# For days when there is no stream, replace viewing hour, number of streamers, and sum of streamers' followers to zero\n",
        "# Drop observations without data on the number of players\n",
        "\n",
        "game_price_players <- merge(game_price_players, game_attributes[, .(app_id, title)], by = \"app_id\", all.x = T)\n",
        "twitch_stream_merged <- merge(twitch_viewing_hours, game_price_players, by = c(\"title\", \"date\"), all = T)\n",
        "overlapped_games <- intersect(twitch_viewing_hours$title, game_price_players$title)\n",
        "print(paste(length(overlapped_games), \"unique games that have Steam player data and Twitch streaming data\"))\n",
        "twitch_stream_merged <- twitch_stream_merged[title %in% overlapped_games & date >= \"2017-01-01\"]\n",
        "twitch_stream_merged[is.na(viewing_hour), viewing_hour := 0]\n",
        "twitch_stream_merged[is.na(num_streamers), num_streamers := 0]\n",
        "twitch_stream_merged[is.na(num_streamers_weighted), num_streamers_weighted := 0]\n",
        "twitch_stream_merged <- twitch_stream_merged[!is.na(player_count), ]\n",
        "twitch_stream_merged <- twitch_stream_merged[order(title, date)]\n",
        "\n",
        "# Now examine the correlation between the number of streamers who broadcast the game and the number of players\n",
        "#   First, for each of the top-9 paid games we obtain from step 2, plot the number of players and the number of streamers.\n",
        "#   Separately, plot the number of players against the log viewing hours + 1 (so if viewing_hours = 0, log(viewing_hours + 1)\n",
        "#   is not NaN). In both cases, title the graph with the correlation coefficient between the two covariates.\n",
        "#   Alternatively, you can plot viewing hours, players, and number of streamers against time, just like what we did in step 2.\n",
        "\n",
        "# NOTE: I also de-trended the data. You do not have to do this.\n",
        "pdf(\"../output/plot_players_and_streamers.pdf\", width = 15, height = 15)\n",
        "par(mfrow = c(3, 3))\n",
        "for (i in 1:9) {\n",
        "    aid <- top_9_paid_games$app_id[i]\n",
        "    dat <- twitch_stream_merged[app_id == aid][order(date)]\n",
        "    reg_1 <- lm(log(player_count + 1) ~ date, dat)\n",
        "    reg_2 <- lm(log(num_streamers + 1) ~ date, dat)\n",
        "    corcoef <- cor(reg_1$residuals, reg_2$residuals)\n",
        "    plot(reg_1$residuals ~ dat$date, type = 'l', col = \"blue\",\n",
        "         main = paste(top_9_paid_games$title[i], \", corr = \", round(corcoef, 2)),\n",
        "         xlab = \"date\", ylab = \"detrended log players and log streamers\")\n",
        "    points(reg_2$residuals ~ dat$date, type = 'l', lty = 2)\n",
        "}\n",
        "dev.off()\n",
        "\n",
        "pdf(\"../output/plot_players_and_log_viewers.pdf\", width = 15, height = 15)\n",
        "par(mfrow = c(3, 3))\n",
        "for (i in 1:9) {\n",
        "    aid <- top_9_paid_games$app_id[i]\n",
        "    dat <- twitch_stream_merged[app_id == aid][order(date)]\n",
        "    reg_1 <- lm(log(player_count + 1) ~ date, dat)\n",
        "    reg_2 <- lm(log(viewing_hour + 1) ~ date, dat)\n",
        "    corcoef <- cor(reg_1$residuals, reg_2$residuals)\n",
        "    plot(reg_1$residuals ~ dat$date, type = 'l', col = \"blue\",\n",
        "         main = paste(top_9_paid_games$title[i], \", corr = \", round(corcoef, 2)),\n",
        "         xlab = \"date\", ylab = \"detrended log players and log viewing hours\")\n",
        "    points(reg_2$residuals ~ dat$date, type = 'l', lty = 2)\n",
        "}\n",
        "dev.off()\n",
        "\n",
        "\n",
        "# ALTERNATIVE: plot players against viewers/streamers\n",
        "# pdf(\"../output/plot_players_and_streamers.pdf\", width = 15, height = 15)\n",
        "# par(mfrow = c(3, 3))\n",
        "# for (i in 1:9) {\n",
        "#     aid <- top_9_paid_games$app_id[i]\n",
        "#     dat <- twitch_stream_merged[app_id == aid][order(date)]\n",
        "#     corcoef <- cor(log(dat$player_count), dat$num_streamers)\n",
        "#     plot(player_count ~ num_streamers, data = dat, log = \"y\", col = \"blue\",\n",
        "#          main = paste(top_9_paid_games$title[i], \", corr = \", round(corcoef, 2)),\n",
        "#          xlab = \"number of streamers\", ylab = \"number of players\")\n",
        "# }\n",
        "# dev.off()\n",
        "#\n",
        "# pdf(\"../output/plot_players_and_log_viewers.pdf\", width = 15, height = 15)\n",
        "# par(mfrow = c(3, 3))\n",
        "# for (i in 1:9) {\n",
        "#     aid <- top_9_paid_games$app_id[i]\n",
        "#     dat <- twitch_stream_merged[app_id == aid][order(date)]\n",
        "#     corcoef <- cor(log(dat$player_count), log(dat$viewing_hour + 1))\n",
        "#     plot(log(dat$player_count) ~ log(dat$viewing_hour + 1), col = \"blue\",\n",
        "#          main = paste(top_9_paid_games$title[i], \", corr = \", round(corcoef, 2)),\n",
        "#          xlab = \"log number of viewers\", ylab = \"log number of players\")\n",
        "# }\n",
        "# dev.off()\n",
        "\n"
      ]
    }
  ]
}